sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  app: stark-dusk-71758
  provider: heroku
  api_key: 
    secure: a0393d1c-60be-4cad-bb06-cca759847edb
